# Generated by Django 4.0.4 on 2022-05-19 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoblog', '0004_alter_note_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='parent_date',
        ),
        migrations.AddField(
            model_name='task',
            name='parent_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todoblog.task_date'),
        ),
    ]
