# Generated by Django 4.0.4 on 2022-05-19 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todoblog', '0005_remove_note_parent_date_task_parent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_date',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
