# Generated by Django 4.0.4 on 2022-06-08 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoblog', '0006_task_date_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
