# Generated by Django 4.0.4 on 2022-06-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='div_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
