# Generated by Django 4.0.4 on 2022-06-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_div_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date_2',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
