# Generated by Django 4.0.4 on 2022-05-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0007_profile_view_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='logged_in_device_setting',
            field=models.BooleanField(default=False),
        ),
    ]
