# Generated by Django 4.0.4 on 2022-05-15 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0008_profile_logged_in_device_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
